#!/bin/bash

# =============================================================================
# First-Level Voxel-Wise fMRI Analysis Job Launcher
# =============================================================================
#
# This script launches SLURM jobs for first-level voxel-wise fMRI analysis.
# It automatically detects and launches scripts generated by create_1st_voxelWise.py
#
# Usage:
#   ./launch_1st_voxelWise.sh                    # Launch all available scripts
#   ./launch_1st_voxelWise.sh --phase phase2     # Launch only phase2 scripts
#   ./launch_1st_voxelWise.sh --phase phase3     # Launch only phase3 scripts
#   ./launch_1st_voxelWise.sh --dry-run          # Show what would be launched
#
# Author: Xiaoqian Xiao (xiao.xiaoqian.320@gmail.com)
#
# =============================================================================

# =============================================================================
# CONFIGURATION
# =============================================================================

# Base directory for first-level scripts
SCRIPTS_BASE_DIR="/gscratch/scrubbed/fanglab/xiaoqian/NARSAD/work_flows/firstLevel_timeEffect"

# Default settings
PHASE=""
DRY_RUN=false

# =============================================================================
# ARGUMENT PARSING
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --phase)
            PHASE="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "OPTIONS:"
            echo "  --phase PHASE     Specific phase to process (phase2, phase3)"
            echo "  --dry-run         Show what would be launched without submitting"
            echo "  --help            Show this help message"
            echo ""
            echo "EXAMPLES:"
            echo "  $0                                    # Launch all available scripts"
            echo "  $0 --phase phase2                     # Launch only phase2 scripts"
            echo "  $0 --phase phase3                     # Launch only phase3 scripts"
            echo "  $0 --dry-run                          # Show what would be launched"
            exit 0
            ;;
        *)
            echo "Error: Unknown option: $1" >&2
            echo "Use --help for usage information" >&2
            exit 1
            ;;
    esac
done

# =============================================================================
# SCRIPT DISCOVERY AND LAUNCHING
# =============================================================================

echo "=========================================="
echo "First-Level Voxel-Wise fMRI Analysis Job Launcher"
echo "=========================================="

if [[ -n "$PHASE" ]]; then
    echo "Phase filter: $PHASE"
fi

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN MODE - No jobs will be submitted"
fi

echo "=========================================="

# Function to launch scripts from a specific phase directory
launch_scripts_from_phase() {
    local phase="$1"
    local phase_dir="$SCRIPTS_BASE_DIR/$phase"
    
    if [[ ! -d "$phase_dir" ]]; then
        echo "Phase directory not found: $phase_dir"
        return
    fi
    
    echo "Processing phase: $phase"
    echo "Directory: $phase_dir"
    
    # Find all SLURM scripts in the phase directory
    local scripts_found=0
    local scripts_launched=0
    
    for script in "$phase_dir"/*.sh; do
        # Check if file exists and is a regular file
        if [[ -f "$script" ]]; then
            scripts_found=$((scripts_found + 1))
            
            if [[ "$DRY_RUN" == true ]]; then
                echo "  [DRY RUN] Would submit: $(basename "$script")"
            else
                echo "  Submitting: $(basename "$script")"
                sbatch "$script"
                scripts_launched=$((scripts_launched + 1))
            fi
        fi
    done
    
    if [[ $scripts_found -eq 0 ]]; then
        echo "  No SLURM scripts found in: $phase_dir"
    else
        if [[ "$DRY_RUN" == true ]]; then
            echo "  [DRY RUN] Found $scripts_found scripts (would launch $scripts_found)"
        else
            echo "  Found $scripts_found scripts, launched $scripts_launched"
        fi
    fi
    
    echo ""
}

# Determine which phases to process
if [[ -n "$PHASE" ]]; then
    # Process only specified phase
    if [[ "$PHASE" == "phase2" || "$PHASE" == "phase3" ]]; then
        launch_scripts_from_phase "$PHASE"
    else
        echo "Error: Invalid phase '$PHASE'. Valid phases are: phase2, phase3"
        exit 1
    fi
else
    # Process all available phases
    for phase in "phase2" "phase3"; do
        launch_scripts_from_phase "$phase"
    done
fi

echo "=========================================="
echo "Job launching completed!"
echo "=========================================="

if [[ "$DRY_RUN" == true ]]; then
    echo ""
    echo "To actually launch the jobs, run without --dry-run:"
    cmd="$0"
    [[ -n "$PHASE" ]] && cmd="$cmd --phase $PHASE"
    echo "  $cmd"
fi
